name: "🔧 New Unsolved Problem"
description: "List a problem you’d like someone to solve"
title: "[Open Problem] "
labels: ["unsolved"]
body:
  - type: input
    id: category
    attributes:
      label: Category
      placeholder: "e.g. Academia, Government, Private Company"
  - type: dropdown
    id: reward
    attributes:
      label: Reward / Budget
      options:
        - "No bounty (open research)"
        - "< $1 000"
        - "$1 000 – $10 000"
        - "> $10 000"
  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: "Short but complete statement of the challenge"
  - type: input
    id: contact
    attributes:
      label: Contact
      placeholder: "email@example.com or GitHub username"
