name: "New Unsolved Problem"
description: "Submit a problem you'd like solved"
title: "[Problem] "
labels: ["unsolved"]
body:
  - type: input
    id: category
    attributes:
      label: Category
      placeholder: "Academia, Government, Company …"
  - type: dropdown
    id: reward
    attributes:
      label: Reward / Budget
      options:
        - "No bounty"
        - "< $1 000"
        - "$1 000 – $10 000"
        - "> $10 000"
  - type: textarea
    id: description
    attributes:
      label: Problem description
      description: "Short but complete summary"
  - type: input
    id: contact
    attributes:
      label: Contact
      placeholder: "email@example.com"
